### ISSUE TITLE
Files aren't appearing in s3 bucket as expected, even though I get success message

### ISSUE THREAD

**Issue by cbrawn** [bypasslane/sftp-to-s3#11]
Hi,

Everything is running through the code as a success in Lambda and the SFTP side of things is working, however the new files don't appear in S3 bucket.  I've included the bucket name, access key id, secretAccessKey and region, I wondered in there was anything that need to be included in the putBatch function in uploadToS3.js?  

I've also noticed that the Put Function isn't returned in the sftp-to-s3, am I missing something?  

Thanks

**Comment by txssseal** [comment]
Let me investigate this.

**Comment by cbrawn** [comment]
I've taken a look today and the files are appearing, thank you @txssseal

**Comment by txssseal** [comment]
Great news :)

Please feel free to contribute to the package!

**Comment by sunkhanna** [comment]
Hi cbrawn,

Can you please share a sample code how you are able to upload the file on s3?I am using private ip and also my lambda and ec2 both are in default vpc and I have done subnet settings also,not sure what is wrong.

const SftpToS3 = require("sftp-to-s3");
var fs = require("fs");

const config = {
  sftp: {
    host: "xx.xx.xx.xx",
    username: "ubuntu",
    //  password: process.env.password,
    port: 22,
    privateKey: fs.readFileSync("/home/ubuntu/.ssh/authorized_keys")
  },
  aws: {
    bucket: "sftptest",
    accessKeyId: "AKID",
    secretAccessKey: "SECRET",
    region: "us-east-1"
  },
  fileDownloadDir: "/home/ubuntu/",
  completedDir: "/completed-uploads/"
};

exports.handler = function(event, context, callback) {
  SftpToS3.batch(config)
    .then(success => {
      console.log(success);
    })
    .catch(err => {
      console.error(err);
    });
};
