### ISSUE TITLE
Update npm package to include bug fix for issue 17 and close issue

### ISSUE THREAD

**Issue by lady3bean** [bypasslane/sftp-to-s3#18]
This issue https://github.com/txssseal/sftp-to-s3/issues/17 has a fix, but that package on npm is not updated with it. Please consider updating the package and closing this issue, as I just debugged it and fixed it myself and was about to make a PR, but when I forked the repo I saw the change had already been made, but only updated on github.

**Comment by txssseal** [comment]
aha!  Thank you
