### ISSUE TITLE
How do I run the tests?

### ISSUE THREAD

**Issue by jarro2783** [bypasslane/sftp-to-s3#3]
I'd like to make a couple of tiny improvements, but I can't run the tests. If I run `npm run test` it says `No gulpfile found`.

I'm not a node developer, so I don't know if I'm missing something. Is there a way to run the tests at the moment?

**Comment by txssseal** [comment]
You have to run the mocha command.  I see have a pr that is fixing this, I will merge and make a new release. Thanks for your contribution!
